log: Add comments to logger interfaces
hyperledger-labs/go-perun pull request #278
Opened 2021-12-03 12:47 UTC by matthiasgeihs

Closes #262

2021-12-03 13:32 UTC, manoranjith commented on log/log.go
> +	// Traceln logs a message at level Trace.
Add `Arguments are handled in the manner of fmt.Println.`

2021-12-03 13:33 UTC, manoranjith requested changes
Have one suggestion.

2021-12-03 14:27 UTC, matthiasgeihs commented
Addressed your comment. Please have another look and feel free to merge.

2021-12-06 11:12 UTC, matthiasgeihs commented
rebased

2021-12-06 11:16 UTC, manoranjith approved these changes

2021-12-06 11:17 UTC, merged