Egoistic funding
hyperledger-labs/go-perun pull request #397
Opened 2024-02-15 09:19 UTC by sophia1ch

## Description:
This PR builds upon the changes introduced in https://github.com/hyperledger-labs/perun-eth-backend/pull/45 by extending egoistic funding to cross-chain swaps in the eth-backend.

In this update, we introduce a map for each chain, designating whether a chain is considered egoistic or not. This distinction is crucial in determining the funding order for different chains, ensuring that egoistic chains are funded last.

2024-02-16 17:03 UTC, cryptphil requested changes

2024-02-16 17:03 UTC, cryptphil commented on client/proposal.go
> +func (r *ProposalResponder) SetEgoisticChain(egoistic multi.LedgerID) {
So you can only set the egoistic flag when you receive a proposal? Can't you set this in beforehand when initializing the funders? In the case of Perun-X, the hub would just set this for all chains?

2024-02-19 09:22 UTC, NhoxxKienn commented
I think the protocol is to merge first to our fork before create a PR here, right?

2024-02-23 10:58 UTC, cryptphil commented
> I think the protocol is to merge first to our fork before create a PR here, right?

No, in general, you always merge to the hyperledger org main and then only sync this fork on perun-network.

2024-02-23 11:05 UTC, cryptphil commented on client/proposal.go
> +func (r *ProposalResponder) SetEgoisticChain(egoistic multi.LedgerID) {
Hm okay I see, thanks.

2024-02-23 11:06 UTC, cryptphil commented on client/proposal.go
> +func (r *ProposalResponder) SetEgoisticChain(egoistic multi.LedgerID) {
Hmm okay, I understand, thanks.

2024-03-06 16:51 UTC, cryptphil commented on MAINTAINERS.md
> +|-------------------|----------------------------------------------------|----------------|
Minor: The authors are usually sorted alphabetically by their last name

2024-03-10 16:44 UTC, cryptphil approved these changes

2024-03-12 12:50 UTC, merged