Simplify funder interface
hyperledger-labs/go-perun pull request #74
Opened 2021-05-13 14:25 UTC by matthiasgeihs

Closes #72

2021-05-16 16:02 UTC, ggwpez commented
I dont really like the concept that the `Depositor` is now additionally used as an account storage.  
You could also change the `DepositorMap` to a map which holds *both* a `Depositor` and an `Account`. Then you would not need to change much in the logic of the `Depositor`s.

2021-05-16 16:04 UTC, ggwpez requested changes

2021-05-16 16:04 UTC, ggwpez commented on backend/ethereum/channel/depositor.go
> +		Account() accounts.Account
If you want to store the account in the `Depositor`, you could also remove it from the `DepositReq` and remove this function.

2021-05-16 16:04 UTC, ggwpez commented on backend/ethereum/channel/depositor.go
>  	// funding. Depositor are reusable such that one Depositor per asset is enough.
The comment was designed for stateless `Depositor`s, so this is wrong now.

2021-05-16 16:04 UTC, ggwpez commented on backend/ethereum/channel/eth_depositor.go
>  // It has no state and is therefore completely reusable.
Comment out-dated.

2021-05-16 16:04 UTC, ggwpez commented on backend/ethereum/channel/erc20_depositor.go
>  // It is bound to a token but can be reused to deposit multiple times.
It is now also bound to an `Account`.

2021-05-20 09:56 UTC, matthiasgeihs commented
> I dont really like the concept that the `Depositor` is now additionally used as an account storage.
> You could also change the `DepositorMap` to a map which holds _both_ a `Depositor` and an `Account`. Then you would not need to change much in the logic of the `Depositor`s.

Why don't you like it?

At first I was considering to do as you suggest (i.e., keep Depositor and Account separate and use a map from Asset to struct{Depositor, Account}). However, after thinking about it, I didn't see a reason why they should be separated. Logically, it makes sense to me that when you create a depositor, you also specify the account for that depositor. The construction of a funder is also more convenient that way, as you need to construct one object less than before.

2021-05-20 13:56 UTC, merged